# Generated by Django 2.0.7 on 2018-11-30 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20181130_2244'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_package', models.CharField(max_length=100)),
                ('price', models.FloatField(verbose_name='Ціна за пакет')),
                ('lenght_discription', models.TextField()),
                ('short_discription', models.TextField(max_length=200)),
                ('users', models.ManyToManyField(related_name='Користувачі', to='polls.User')),
            ],
        ),
    ]
