# Generated by Django 2.0.7 on 2018-11-30 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_package'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ganre_Of_Package',
            fields=[
                ('packages', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='polls.Package')),
                ('name_of_ganre', models.CharField(max_length=25)),
            ],
        ),
    ]
