# Generated by Django 2.0.7 on 2018-11-30 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_ganre_of_package'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ask', models.CharField(max_length=50)),
                ('answer', models.CharField(max_length=100)),
                ('selected_package_id', models.IntegerField()),
                ('number_of_credit_card', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('image_ask', models.ImageField(upload_to='')),
                ('help', models.TextField(max_length=250)),
            ],
        ),
    ]
