# Generated by Django 2.0.7 on 2018-11-30 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_match', models.CharField(max_length=50)),
                ('ask', models.CharField(max_length=50)),
                ('answer_1', models.TextField()),
                ('answer_2', models.TextField()),
                ('image_of_match', models.ImageField(upload_to='')),
                ('help', models.TextField()),
            ],
        ),
    ]
