# Generated by Django 2.0.7 on 2018-11-30 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_match'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mode_Of_Study',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_for_presentation', models.ImageField(blank=True, upload_to='Mode_Of_Study')),
                ('ask_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Ask')),
                ('match_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Match')),
                ('mode_of_study_to_package', models.ManyToManyField(to='polls.Package')),
                ('test_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Test')),
            ],
        ),
    ]
