# Generated by Django 2.0.7 on 2018-12-01 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_mode_of_study'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Ask_body',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Answer_list')),
            ],
        ),
        migrations.CreateModel(
            name='Ask_mode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_ask', models.ImageField(upload_to='')),
                ('ask_body_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Ask_body')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Help_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('help', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Question_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ask', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Test_body',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Answer_list')),
                ('help_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Help_list')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Question_list')),
            ],
        ),
        migrations.CreateModel(
            name='Test_mode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_of_test', models.ImageField(upload_to='')),
                ('test_body_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Test_body')),
            ],
        ),
        migrations.RenameField(
            model_name='user',
            old_name='surname',
            new_name='last_name',
        ),
        migrations.RemoveField(
            model_name='ganre_of_package',
            name='packages',
        ),
        migrations.RemoveField(
            model_name='mode_of_study',
            name='match_id',
        ),
        migrations.RemoveField(
            model_name='mode_of_study',
            name='mode_of_study_to_package',
        ),
        migrations.AddField(
            model_name='ganre_of_package',
            name='ganre_id',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='polls.Package'),
        ),
        migrations.AddField(
            model_name='ganre_of_package',
            name='id',
            field=models.AutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mode_of_study',
            name='description',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mode_of_study',
            name='name_of_mos',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mode_of_study',
            name='text_for_read',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='package',
            name='mode_of_study_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='polls.Mode_Of_Study'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='number_of_credir_card',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mode_of_study',
            name='ask_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Ask_mode'),
        ),
        migrations.AlterField(
            model_name='mode_of_study',
            name='test_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Test_mode'),
        ),
        migrations.DeleteModel(
            name='Ask',
        ),
        migrations.DeleteModel(
            name='Match',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.AddField(
            model_name='ask_body',
            name='help_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Help_list'),
        ),
        migrations.AddField(
            model_name='ask_body',
            name='question_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Question_list'),
        ),
        migrations.AddField(
            model_name='mode_of_study',
            name='comment_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='polls.Comment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='comment_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='polls.Comment'),
            preserve_default=False,
        ),
    ]
